using HTCANXE.Class;
using HTCANXE.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Forms;

namespace HTCANXE
{
    public partial class frm_edit_congtrinh : Form
    {
        public int idCongtrinh = 0;
        //Định nghĩa delegate
        public delegate void DelSendMsg(string msg);
        //khạ báo biến kiểu delegate
        public DelSendMsg SendMsg;
        //private List<KHACHHANG> lstKhachhangs;
        public class comboxItem
        {
            public string Id { get; set; }
            public string Name { get; set; }
        }
       
        public frm_edit_congtrinh()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            cbo_khachhang.Properties.DataSource = Common.db.KHACHHANGs;
            // This line of code is generated by Data Source Configuration Wizard
            lue_tinhthanh.Properties.DataSource = Common.db.TINHTHANHs;
        }
        private void btn_huy_Click(object sender, EventArgs e)
        {
            this.Close();
        }
        private void btn_luu_Click(object sender, EventArgs e)
        {
            
            var congty = ((KHACHHANG)cbo_khachhang.Properties.GetRowByKeyValue(cbo_khachhang.EditValue)).Ma;
            var tinhthanh = ((TINHTHANH)lue_tinhthanh.Properties.GetRowByKeyValue(lue_tinhthanh.EditValue)).Ma;
            if (idCongtrinh != 0)
            {
                Common.db = new DataCanXeDataContext(Common.gConn);
                CONGTRINH newcongtrinh = Common.db.CONGTRINHs.Single(n => n.ID == idCongtrinh);
                newcongtrinh.Ten = txt_tencongtrinh.Text;
                newcongtrinh.KhachHang = congty;
                newcongtrinh.TinhThanh = tinhthanh;
                newcongtrinh.DiaChi = txt_diachi.Text;
                Common.db.SubmitChanges();
            }
            else
            {
                Common.db = new DataCanXeDataContext(Common.gConn);
                CONGTRINH newcongtrinh = new CONGTRINH();
                newcongtrinh.ID = Common.db.CONGTRINHs.Max(n => n.ID) + 1;
                newcongtrinh.Ten = txt_tencongtrinh.Text;
                newcongtrinh.KhachHang = congty;
                newcongtrinh.TinhThanh = tinhthanh;
                newcongtrinh.DiaChi = txt_diachi.Text;
                newcongtrinh.IsActive = true;
                newcongtrinh.CreateDate=DateTime.Now;
                newcongtrinh.IsDelete = false;
                Common.db.CONGTRINHs.InsertOnSubmit(newcongtrinh);
                Common.db.SubmitChanges();
            }
            SendMsg.Invoke("");
            this.Close();
        }
        private void GetDataCombobox()
        {
            if (idCongtrinh != 0)
            {
                Common.db = new DataCanXeDataContext(Common.gConn);
                var resurt = Common.db.CONGTRINHs.Single(n => n.ID == idCongtrinh);
                txt_tencongtrinh.Text = resurt.Ten.ToString();
                cbo_khachhang.Text = resurt.KhachHang.ToString();
                txt_diachi.Text = resurt.DiaChi.ToString();
                lue_tinhthanh.Text = resurt.TinhThanh.ToString();
            }
        }
        private void frm_edit_congtrinh_Load(object sender, EventArgs e)
        {
            Common.db = new DataCanXeDataContext(Common.gConn);
            txt_macongtrinh.Text = idCongtrinh.ToString();
            GetDataCombobox();
        }
    }
}
