using HTCANXE.Model;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Windows.Forms;

namespace HTCANXE
{
    public partial class frm_edit_loaihang : Form
    {
        public string Mahang = string.Empty;
        //Định nghĩa delegate
        public delegate void DelSendMsg(string msg);
        //khạ báo biến kiểu delegate
        public DelSendMsg SendMsg;

        public frm_edit_loaihang()
        {
            InitializeComponent();
            Common.db = new DataCanXeDataContext(Common.gConn);
            // This line of code is generated by Data Source Configuration Wizard
            //cbo_nhom.Properties.DataSource = Common.db.HANGHOAs;
            // This line of code is generated by Data Source Configuration Wizard
            // This line of code is generated by Data Source Configuration Wizard
            //cbo_loaixuat.Properties.DataSource = Common.db.LOAICANs;
            // This line of code is generated by Data Source Configuration Wizard
            cbo_nhom.Properties.DataSource = Common.db.NHOMHANGHOAs;
            // This line of code is generated by Data Source Configuration Wizard
            cbo_loaixuat.Properties.DataSource = Common.db.LOAICANs;
        }
        private void GetDataCombobox()
        {

            if (Mahang != string.Empty)
            {
                Common.db = new DataCanXeDataContext(Common.gConn);
                var hanghoa = Common.db.HANGHOAs.Where(n => n.Ma == Mahang).SingleOrDefault();

                txt_ma.Text = hanghoa.Ma.ToString();
                txt_ten.Text = hanghoa.Ten.ToString();
                txt_solo.Text = hanghoa.SoLo.ToString();
                cbo_nhom.Text = hanghoa.Nhom.ToString();
                cbo_loaixuat.Text = hanghoa.NhomCan.ToString();
                // txt_ghichu.Text = hanghoa.ghi.ToString();
                txt_ma.Enabled = false;
            }
        }

        private void frm_edit_loaihang_Load(object sender, EventArgs e)
        {
            GetDataCombobox();
        }

        private void btn_huy_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void btn_luu_Click(object sender, EventArgs e)
        {
            var nhomhang = ((NHOMHANGHOA)cbo_nhom.Properties.GetRowByKeyValue(cbo_nhom.EditValue)).Ma;
            var loaixuat = ((LOAICAN)cbo_loaixuat.Properties.GetRowByKeyValue(cbo_loaixuat.EditValue)).Ma;
            if (Mahang != string.Empty)
            {
                Common.db = new DataCanXeDataContext(Common.gConn);
                var hanghoa = Common.db.HANGHOAs.Where(n => n.Ma == Mahang).SingleOrDefault();
                hanghoa.Ma = Mahang.ToString();
                hanghoa.Ten = txt_ten.Text;
                hanghoa.Nhom = nhomhang;
                hanghoa.NhomCan = loaixuat;
                hanghoa.SoLo = Int32.Parse(txt_solo.Text.ToString());
                hanghoa.IsActive = true;
                // hanghoa.GHICHU = txt_ghichu.Text;
                Common.db.SubmitChanges();
            }
            else
            {
                Common.db = new DataCanXeDataContext(Common.gConn);
                HANGHOA hanghoa = new HANGHOA();
                hanghoa.Ma = txt_ma.Text;
                hanghoa.Ten = txt_ten.Text;
                hanghoa.Nhom = nhomhang;
                hanghoa.NhomCan = loaixuat;
                hanghoa.SoLo = Int32.Parse(txt_solo.Text.ToString());
                hanghoa.IsActive = true;
                // hanghoa. = txt_ghichu.Text;
                Common.db.HANGHOAs.InsertOnSubmit(hanghoa);
                Common.db.SubmitChanges();
            }
            SendMsg.Invoke("");
            this.Close();
        }
    }
}
