using System;
using System.Linq;
using System.Windows.Forms;
using HTCANXE.Model;

namespace HTCANXE.NghiepVu
{
    public partial class frm_suaphieucan : Form
    {
        public int id_phieu;
        public frm_suaphieucan()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
           
        }
        private void btn_huy_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void btn_capnhat_Click(object sender, EventArgs e)
        {
            var khachhang = ((KHACHHANG)cbo_congty.Properties.GetRowByKeyValue(cbo_congty.EditValue)).Ma;
            var congtrinh = ((CONGTRINH)cbo_congtrinh.Properties.GetRowByKeyValue(cbo_congtrinh.EditValue)).ID;
            var loaihang = ((HANGHOA)cbo_loaihang.Properties.GetRowByKeyValue(cbo_loaihang.EditValue)).Ma;
            var noixuat = ((NOIXUAT)cbo_noixuat.Properties.GetRowByKeyValue(cbo_noixuat.EditValue)).Ma;

            Common.db = new DataCanXeDataContext(Common.gConn);
            CANXE oldcanxe = Common.db.CANXEs.Single(o => o.id == id_phieu);
            oldcanxe.LoaiHang = loaihang;
            oldcanxe.CongTrinh = congtrinh;
            oldcanxe.CongTy = khachhang;
            oldcanxe.NoiXuat = noixuat;
            //oldcanxe.SoNiem = txt_soniem.Text;
            Common.db.SubmitChanges();
            Close();
        }

        private void frm_suaphieucan_Load(object sender, EventArgs e)
        {
            Common.db = new DataCanXeDataContext(Common.gConn);
            cbo_loaihang.Properties.DataSource = Common.db.HANGHOAs;
            // This line of code is generated by Data Source Configuration Wizard
            cbo_congtrinh.Properties.DataSource = Common.db.CONGTRINHs;
            // This line of code is generated by Data Source Configuration Wizard
            cbo_congty.Properties.DataSource = Common.db.KHACHHANGs;
            // This line of code is generated by Data Source Configuration Wizard
            cbo_noixuat.Properties.DataSource = Common.db.NOIXUATs;

            var result = Common.db.Fn_GetPhieuCanXe("ALL", "ALL", 1, 1, 0, id_phieu).SingleOrDefault();
            if (result != null)
            {
                txt_sophieu.Text = result.SoPhieu;
                txt_soxe.Text = result.SoXe;
                txt_soromooc.Text = result.SoRomooc;
               // txt_soniem.Text = result.SoNiem;
                cbo_loaihang.Text = result.MaHang;
                cbo_congtrinh.Text = result.MaCongTrinh.ToString();
                cbo_congty.Text = result.MaCongTy;
                cbo_noixuat.Text = result.NoiXuat;
            }
        }
    }
}
